name              'logrotate'
maintainer        'BitPusher, LLC'
maintainer_email  'ops@bitpusher.com'
license           'Apache-2.0'
description       'Installs logrotate package and provides a resource for managing logrotate configs'
version           '2.2.2'
chef_version '>= 12.5'
