driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install cronie

- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install lsof which initscripts net-tools wget net-tools cronie

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools cronie

- name: debian-7
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release cron apt-transport-https -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release cron apt-transport-https -y

suites:
  - name: apt_repos
    run_list:
    - recipe[test::apt_repos]
    includes: [
      'debian-7',
      'debian-8'
    ]
  - name: cron
    run_list:
    - recipe[test::cron]
  - name: cron_d
    run_list:
    - recipe[test::cron_d]
  - name: directory
    run_list:
    - recipe[test::directory]
  - name: groups
    run_list:
    - recipe[test::groups]
  - name: users
    run_list:
    - recipe[test::users]
  - name: yum_repos
    run_list:
    - recipe[test::yum_repos]
    includes: [
      'amazonlinux',
      'centos-6',
      'centos-7'
    ]
  - name: iptables_d
    run_list:
    - recipe[test::iptables_d]
    includes: [
      'centos-6',
      'centos-7'
    ]
  - name: sudoers_d
    run_list:
    - recipe[test::sudoers_d]
  - name: init_d
    run_list:
    - recipe[test::init_d]
    includes: [
      'amazonlinux',
      'centos-6'
    ]
