##  EMR CLUSTER
module "emr" {
  source                              = "../../site-modules/emr/0.1.0"
  name                                = "emr"
  subnet_group_octet                  = "${var.subnet_group_octets["emr"]}"
  emr_release_label                   = "emr-5.25.0"
  master_instance_type                = "m4.large"
  master_instance_count               = "1"
  core_instance_type                  = "m4.large"
  core_instance_count                 = "3"
  core_instance_ebs_size              = "200"
  core_instance_ebs_type              = "gp2"
  core_instance_ebs_vols_per_instance = "1"
  ebs_root_volume_size                = "100"
  env_strings                         = "${local.env_strings}"
  base_strings                        = "${local.base_strings}"
  vpc_strings                         = "${local.vpc-main_strings}"
  vpc_lists                           = "${local.vpc-main_lists}"
  az_count                            = "${var.vpc-main_az_count}"
  chef_strings                        = "${local.chef_strings}"
  chef_lists                          = "${local.chef_lists}"
  chef_iam_policy_count               = "${module.chef.iam_policy_count}"
  terraform_strings                   = "${local.terraform_strings}"
  tags                                = "${local.tags}"
}
output "emr_master_node_cname"  { value = "${module.emr.master_node_cname}" }
