driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[chef-grafana::default]
    attributes:
