name             'bootstrap'
maintainer       'Mike Doty'
maintainer_email 'mdoty@bitpusher.com'
license          'BitPusher'
description      'Bootstrap chef code'
version          '0.0.1'
chef_version     '>= 12.4'
supports         'ubuntu', '>= 14.04'

depends 'users'
