name              'nlbhap-haproxy'
maintainer        'Aaron Cutchin'
maintainer_email  'acutchin@bitpusher.com'
license           'BitPusher'
description       'nlb-haproxy example for reference architecture'
version           '0.0.1'
chef_version      '>= 12.4'
supports          'ubuntu', '>= 14.04'
depends           'haproxy'
