##
##  GALERA EC2 CLUSTER
##
variable "name"                               { type = "string" }
variable "chef_role"                          { type = "string"   default = "" }  ##  DEFAULTS TO var.name
variable "subnet_group_octet"                 { type = "string" }
variable "ami_id"                             { type = "string"   default = "" }  ##  DEFAULTS TO LATEST UBUNTU 18.04 AMI
variable "instance_count_az0"                 { type = "string"   default = 1 }
variable "instance_count_az1"                 { type = "string"   default = 1 }
variable "instance_count_az2"                 { type = "string"   default = 1 }
variable "instance_type"                      { type = "string" }
variable "addl_security_groups"               { type = "list"     default = [] }  ##  ARBITRARY LIST OF SECURITY GROUP IDS TO ATTACH TO INSTANCES
variable "addl_iam_policy_arns"               { type = "list"     default = [] }  ##  ARBITRARY LIST OF IAM POLICY ARNS TO ATTACH TO INSTANCE IAM ROLE
variable "az_count"                           { type = "string" }
##  ROOT EBS VOLUME
variable "root_volume_size"                   { type = "string"   default = "" }  ##  DEFAULTS TO env_strings["default_root_volume_size"]
variable "root_volume_type"                   { type = "string"   default = "" }  ##  DEFAULTS TO env_strings["default_root_volume_type"]
variable "root_volume_iops"                   { type = "string"   default = "" }  ##  DEFAULTS TO env_strings["default_root_volume_iops"]
variable "root_volume_delete_on_termination"  { type = "string"   default = "" }  ##  DEFAULTS TO env_strings["default_root_volume_delete_on_termination"]
##  MYSQL EBS VOLUMES
variable "mysql-binlog-vol-iops"              { type = "string"   default = "" }  ##  IF EMPTY AND TYPE IS IO1, AWS ASSIGNS A MINIMUM IOPS BASED ON THE VOL SIZE
variable "mysql-binlog-vol-size"              { type = "string"   default = "40" }
variable "mysql-binlog-vol-type"              { type = "string"   default = "gp2" }
variable "mysql-tmp-vol-iops"                 { type = "string"   default = "" }  ##  IF EMPTY AND TYPE IS IO1, AWS ASSIGNS A MINIMUM IOPS BASED ON THE VOL SIZE
variable "mysql-tmp-vol-size"                 { type = "string"   default = "40" }
variable "mysql-tmp-vol-type"                 { type = "string"   default = "gp2" }

##
##  RDS BACKUP INSTANCE
##
variable "rds-backup_subnet_group_octet"                  { type = "string" }
variable "rds-backup_port"                                { type = "string"   default = "3306" }
variable "rds-backup_addl_security_group_ids"             { type = "list"     default = [] }      ##  SG IDS TO ATTACH TO THE RDS INSTANCE, IN ADDITION TO THE GENERATED ONE AND THE ADMIN SG
variable "rds-backup_multi_az"                            { type = "string"   default = "false" } ##  IF YOU ENABLE THIS, THEN "rds-backup_az" IS IGNORED 
variable "rds-backup_az"                                  { type = "string"   default = "" }      ##  DEFAULTS TO vpc_lists["availability_zones"][0]
variable "rds-backup_engine_major_version"                { type = "string"   default = "5.7" }
variable "rds-backup_engine_minor_version"                { type = "string"   default = "" }      ##  APPENDED TO rds-backup_engine_major_version; RDS WILL USE LATEST MINOR VERSION BY DEFAULT
variable "rds-backup_instance_class"                      { type = "string"   default = "" }      ##  DEFAULTS TO env_strings["default_rds_instance_type"]; CONSULT https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html
variable "rds-backup_allocated_storage"                   { type = "string"   default = "" }      ##  DEFAULTS TO 10
variable "rds-backup_max_allocated_storage"               { type = "string"   default = "0" }
variable "rds-backup_storage_type"                        { type = "string"   default = "gp2" }
variable "rds-backup_iops"                                { type = "string"   default = "0" }
variable "rds-backup_database_name"                       { type = "string"   default = "db" }    ##  ALPHANUMERIC ONLY - NO HYPHENS OR UNDERSCORES
variable "rds-backup_admin_username"                      { type = "string"   default = "admin" }
variable "rds-backup_admin_password"                      { type = "string"   default = "" }      ##  ONLY PRINTABLE ASCII CHARACTERS BESIDES '/', '@', '"', GENERATED BY TF BY DEFAULT
variable "rds-backup_iam_database_authentication_enabled" { type = "string"   default = "false" }
variable "rds-backup_parameters"                          { type = "list"     default = [] }      ##  LIST OF MAPS OF PARAMETERS
##  BACKUPS / FINAL SNAPSHOT
variable "rds-backup_backup_retention_period"             { type = "string"   default = 30 }      ##  BACKUP RETENTION PERIOD IN DAYS
variable "rds-backup_backup_window"                       { type = "string"   default = "" }      ##  "HH24:MM-HH24:MM", AT LEAST 30 MINUTES; RDS ASSIGNS BY DEFAULT
variable "rds-backup_skip_final_snapshot"                 { type = "string"   default = "true" }  ##  THIS IS IGNORED: https://github.com/terraform-providers/terraform-provider-aws/issues/2588
##  DB DELETION PROTECTION
variable "rds-backup_deletion_protection"                 { type = "string"   default = "false" }
##  MAINTENANCE / AUTO-UPGRADES
variable "rds-backup_allow_major_version_upgrade"         { type = "string"   default = "false" }
variable "rds-backup_apply_immediately"                   { type = "string"   default = "false" }
variable "rds-backup_maintenance_window"                  { type = "string"   default = "" }      ##  "DDD:HH24:MM-DDD:HH24:MM"; RDS ASSIGNS BY DEFAULT
##  TERRAFORM RESOURCE CREATION TIMEOUTS
variable "rds-backup_timeouts" {
  type      = "map"
  default   = {
    create  = "40m"
    update  = "80m"
    delete  = "40m"
  }
}
##  CLOUDWATCH LOGS / ENHANCED MONITORING METRICS
##  NOT CURRENTLY CONFIGURING MONITORING FOR THE RDS BACKUP INSTANCE
#variable "rds-backup_enabled_cloudwatch_logs_exports"    { type = "list"     default = [] }
#variable "rds-backup_monitoring_interval"                { type = "string"   default = 0 }
#variable "rds-backup_monitoring_role_arn"                { type = "string"   default = "" }
#variable "rds-backup_monitoring_role_name"                { type = "string"   default = "rds-monitoring-role" }
#variable "rds-backup_create_monitoring_role"              { type = "string"   default = "false" }

##  GENERAL
variable "base_strings"                       { type = "map" }
variable "env_strings"                        { type = "map" }
variable "chef_strings"                       { type = "map" }
variable "chef_lists"                         { type = "map" }
variable "chef_iam_policy_count"              { type = "string" }
variable "terraform_strings"                  { type = "map" }
variable "vpc_strings"                        { type = "map" }
variable "vpc_lists"                          { type = "map" }
variable "tags"                               { type = "map" }
